In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
!pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
! mkdir ~/.kaggle

In [ ]:
! cp kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets download -d shibumohapatra/book-my-show

100% 107k/107k [00:00<00:00, 376kB/s]
100% 107k/107k [00:00<00:00, 376kB/s]


In [ ]:
!unzip book-my-show.zip

Archive:  book-my-show.zip
  inflating: dataset.csv             


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import pandas as pd

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, LeaveOneOut, KFold


import statistics

In [ ]:
data = pd.read_csv("dataset.csv")
data.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0     1                           0              1                   1   
1     2                           1              1                   1   
2     3                           1             -1                   1   
3     4                           1             -1                   1   
4     5                           1             -1                   0   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                         0              0   
1                 1                         1              0   
2                 1                         1              0   
3                 1                         1              0   
4                 1                         1              0   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                  0               0                            0  ...   
1                 -1               1                            0  ...   
2                  0               0                            0  ...   
3                  0               0                            1  ...   
4                  1               1                            0  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1              0          0            0          0   
1            1       1              0          0           -1          0   
2            1       1              1          0            1          0   
3            1       1              0          0            1          0   
4            0       1              0          0           -1          0   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                   0       0  
1             1                       1                   1       0  
2             1                      -1                   0       0  
3             1                       0                   1       0  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [ ]:
x = data.iloc[:,1:-1]
x.head()

having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0                           0              1                   1   
1                           1              1                   1   
2                           1             -1                   1   
3                           1             -1                   1   
4                           1             -1                   0   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                         0              0   
1                 1                         1              0   
2                 1                         1              0   
3                 1                         1              0   
4                 1                         1              0   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  Favicon  \
0                  0               0                            0        1   
1                 -1               1                            0        1   
2                  0               0                            0        1   
3                  0               0                            1        1   
4                  1               1                            0        1   

   ...  RightClick  popUpWidnow  Iframe  age_of_domain  DNSRecord  \
0  ...           1            1       1              0          0   
1  ...           1            1       1              0          0   
2  ...           1            1       1              1          0   
3  ...           1            1       1              0          0   
4  ...           1            0       1              0          0   

   web_traffic  Page_Rank  Google_Index  Links_pointing_to_page  \
0            0          0             1                       1   
1           -1          0             1                       1   
2            1          0             1                      -1   
3            1          0             1                       0   
4           -1          0             1                       1   

   Statistical_report  
0                   0  
1                   1  
2                   0  
3                   1  
4                   1  

[5 rows x 30 columns]

In [ ]:
y=data.iloc[:,-1:]
y.head()

Result
0       0
1       0
2       0
3       0
4       1

In [ ]:
model_knn_uc = KNeighborsClassifier(n_neighbors=3)
model_knn_bes = KNeighborsClassifier(n_neighbors=5)

In [ ]:
model_logReg = LogisticRegression(random_state=0)
model_naiveBayes = GaussianNB()
model_decTree = tree.DecisionTreeClassifier()

In [ ]:
model_randomForest_elli = RandomForestClassifier(n_estimators=50)
model_randomForest_yuz = RandomForestClassifier(n_estimators=100)

In [ ]:
model_svm_rbf = SVC(kernel="rbf")
model_svm_linear = SVC(kernel="linear")

### Train-Test Ayrımı

0.15, 0.2 ve 0.3 oranlarında test kümesi ayrıldı.

In [ ]:
x_train_1, x_test_1, y_train_1, y_test_1 = train_test_split( x, y, test_size=0.15, random_state=0)
x_train_2, x_test_2, y_train_2, y_test_2 = train_test_split( x, y, test_size=0.2, random_state=0)
x_train_3, x_test_3, y_train_3, y_test_3 = train_test_split( x, y, test_size=0.3, random_state=0)

In [ ]:
loo = LeaveOneOut()
kfold_5 = KFold(5)
kfold_10 = KFold(10)

### İş yükünü azaltmak için oluşturulan fonksiyonlar

In [ ]:
def cv_skor_yaz(model, x, y):
  score_loo = cross_val_score(model, x, y, scoring='accuracy',
                          cv=loo)
  print("Leave One Out çapraz doğrulama skoru : ", statistics.mean(score_loo))
  score_kfold_5 = cross_val_score(model, x, y, scoring='accuracy',
                             cv=kfold_5, n_jobs=-1)
  score_kfold_10 = cross_val_score(model, x, y, scoring='accuracy',
                             cv=kfold_10, n_jobs=-1)
  print("5 katlı çapraz doğrulama skoru : ", statistics.mean(score_kfold_5))
  print("10 katlı çapraz doğrulama skoru : ", statistics.mean(score_kfold_10))
  

In [ ]:
def metrik_yaz(y_test, y_pred):
    print("Confusion Matris : \n",confusion_matrix(y_test,y_pred))
    print("Classification Report : \n",classification_report(y_test,y_pred))
    print("Accuracy Score : ",accuracy_score(y_test,y_pred))
    print("F1 Score : ",f1_score(y_test,y_pred, average=None))
    

In [ ]:
def hepsi_egit(x_train_1, y_train_1):
  model_knn_uc.fit(x_train_1, y_train_1)
  model_knn_bes.fit(x_train_1, y_train_1)
  model_logReg.fit(x_train_1, y_train_1)
  model_decTree.fit(x_train_1, y_train_1)
  model_naiveBayes.fit(x_train_1, y_train_1)
  model_randomForest_elli.fit(x_train_1, y_train_1)
  model_randomForest_yuz.fit(x_train_1, y_train_1)
  model_svm_rbf.fit(x_train_1, y_train_1)
  model_svm_linear.fit(x_train_1, y_train_1)

In [ ]:
def hepsi_tahmin(x_test):
  y1 = model_knn_uc.predict(x_test)
  y2 = model_knn_bes.predict(x_test)
  y3 = model_logReg.predict(x_test)
  y4 = model_decTree.predict(x_test)
  y5 = model_naiveBayes.predict(x_test)
  y6 = model_randomForest_elli.predict(x_test)
  y7 = model_randomForest_yuz.predict(x_test)
  y8 = model_svm_rbf.predict(x_test)
  y9 = model_svm_linear.predict(x_test)
  return y1, y2, y3, y4, y5, y6, y7, y8, y9

In [ ]:
def sonuclar(y_test):
  print("------ÜÇ KOMŞULU KNN TEST SONUÇLARI---------")
  metrik_yaz(y_test, y_pred_knnUc)
  print("------BEŞ KOMŞULU KNN TEST SONUÇLARI---------")
  metrik_yaz(y_test, y_pred_knnBes)
  print("------LOJİSTİK REGRESYON TEST SONUÇLARI---------")
  metrik_yaz(y_test, y_pred_logReg)
  print("------KARAR AĞACI TEST SONUÇLARI---------")
  metrik_yaz(y_test, y_pred_decTree)
  print("------NAİVE BAYES TEST SONUÇLARI---------")
  metrik_yaz(y_test, y_pred_NB)
  print("------50 ÜYELİ RANDOM FOREST TEST SONUÇLARI---------")
  metrik_yaz(y_test, y_pred_RF50)
  print("------100 ÜYELİ RANDOM FOREST TEST SONUÇLARI---------")
  metrik_yaz(y_test, y_pred_RF100)
  print("------RBF ÇEKİRDEKLİ SVM TEST SONUÇLARI---------")
  metrik_yaz(y_test, y_pred_svmRbf)
  print("------LİNEAR ÇEKİRDEKLİ SVM TEST SONUÇLARI---------")
  metrik_yaz(y_test, y_pred_svmLin)

### 0.15 oranında ayrılan test kümesi sonuçları

In [ ]:
hepsi_egit(x_train_1, y_train_1)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [ ]:
y_pred_knnUc, y_pred_knnBes, y_pred_logReg, y_pred_decTree, y_pred_NB, y_pred_RF50, y_pred_RF100, y_pred_svmRbf, y_pred_svmLin = hepsi_tahmin(x_test_1)

In [ ]:
sonuclar(y_test_1)

------ÜÇ KOMŞULU KNN TEST SONUÇLARI---------
Confusion Matris : 
 [[697  51]
 [ 20 891]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.97      0.93      0.95       748
           1       0.95      0.98      0.96       911

    accuracy                           0.96      1659
   macro avg       0.96      0.95      0.96      1659
weighted avg       0.96      0.96      0.96      1659

Accuracy Score :  0.9572031344183243
F1 Score :  [0.95153584 0.96168376]
------BEŞ KOMŞULU KNN TEST SONUÇLARI---------
Confusion Matris : 
 [[692  56]
 [ 26 885]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.96      0.93      0.94       748
           1       0.94      0.97      0.96       911

    accuracy                           0.95      1659
   macro avg       0.95      0.95      0.95      1659
weighted avg       0.95      0.95      0.95      1659

Accuracy Score :  0.9505726341169379
F1 Sc

### 0.2 oranında ayrılan test kümesi sonuçları

In [ ]:
hepsi_egit(x_train_2, y_train_2)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [ ]:
y_pred_knnUc, y_pred_knnBes, y_pred_logReg, y_pred_decTree, y_pred_NB, y_pred_RF50, y_pred_RF100, y_pred_svmRbf, y_pred_svmLin = hepsi_tahmin(x_test_2)

In [ ]:
sonuclar(y_test_2)

------ÜÇ KOMŞULU KNN TEST SONUÇLARI---------
Confusion Matris : 
 [[ 948   66]
 [  36 1161]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.96      0.93      0.95      1014
           1       0.95      0.97      0.96      1197

    accuracy                           0.95      2211
   macro avg       0.95      0.95      0.95      2211
weighted avg       0.95      0.95      0.95      2211

Accuracy Score :  0.9538670284938942
F1 Score :  [0.94894895 0.95792079]
------BEŞ KOMŞULU KNN TEST SONUÇLARI---------
Confusion Matris : 
 [[ 946   68]
 [  38 1159]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.96      0.93      0.95      1014
           1       0.94      0.97      0.96      1197

    accuracy                           0.95      2211
   macro avg       0.95      0.95      0.95      2211
weighted avg       0.95      0.95      0.95      2211

Accuracy Score :  0.95205789235639

### 0.3 oranında ayrılan test kümesi sonuçları

In [ ]:
hepsi_egit(x_train_3, y_train_3)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

In [ ]:
y_pred_knnUc, y_pred_knnBes, y_pred_logReg, y_pred_decTree, y_pred_NB, y_pred_RF50, y_pred_RF100, y_pred_svmRbf, y_pred_svmLin = hepsi_tahmin(x_test_3)

In [ ]:
sonuclar(y_test_3)

------ÜÇ KOMŞULU KNN TEST SONUÇLARI---------
Confusion Matris : 
 [[1406   92]
 [  58 1761]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.96      0.94      0.95      1498
           1       0.95      0.97      0.96      1819

    accuracy                           0.95      3317
   macro avg       0.96      0.95      0.95      3317
weighted avg       0.95      0.95      0.95      3317

Accuracy Score :  0.9547784142297256
F1 Score :  [0.94935854 0.95915033]
------BEŞ KOMŞULU KNN TEST SONUÇLARI---------
Confusion Matris : 
 [[1408   90]
 [  59 1760]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.96      0.94      0.95      1498
           1       0.95      0.97      0.96      1819

    accuracy                           0.96      3317
   macro avg       0.96      0.95      0.95      3317
weighted avg       0.96      0.96      0.96      3317

Accuracy Score :  0.95507989146819

In [ ]:
cv_skor_yaz(model_knn_uc,x_test_1 ,y_test_1.values.ravel())

Leave One Out çapraz doğrulama skoru :  0.9095840867992767
5 katlı çapraz doğrulama skoru :  0.9029592691005714
10 katlı çapraz doğrulama skoru :  0.9035596933187294


In [ ]:
cv_skor_yaz(model_knn_bes,x_test_1 ,y_test_1.values.ravel())

Leave One Out çapraz doğrulama skoru :  0.9156118143459916
5 katlı çapraz doğrulama skoru :  0.9114057438212062
10 katlı çapraz doğrulama skoru :  0.9090032858707557


In [ ]:
cv_skor_yaz(model_logReg,x_test_1 ,y_test_1.values.ravel())

Leave One Out çapraz doğrulama skoru :  0.9041591320072333
5 katlı çapraz doğrulama skoru :  0.9029556291631784
10 katlı çapraz doğrulama skoru :  0.9017415115005476


In [ ]:
cv_skor_yaz(model_decTree,x_test_1 ,y_test_1.values.ravel()) 

Leave One Out çapraz doğrulama skoru :  0.9119951778179626
5 katlı çapraz doğrulama skoru :  0.9101972846067048
10 katlı çapraz doğrulama skoru :  0.8987477181453085


In [ ]:
cv_skor_yaz(model_randomForest_elli ,x_test_1 ,y_test_1.values.ravel()) 

Leave One Out çapraz doğrulama skoru :  0.9367088607594937
5 katlı çapraz doğrulama skoru :  0.9355094092381611
10 katlı çapraz doğrulama skoru :  0.9349142022635999


In [ ]:
cv_skor_yaz(model_randomForest_yuz,x_test_1 ,y_test_1.values.ravel()) 

Leave One Out çapraz doğrulama skoru :  0.945750452079566
5 katlı çapraz doğrulama skoru :  0.9361118188767154
10 katlı çapraz doğrulama skoru :  0.9379225994888646


In [ ]:
cv_skor_yaz(model_naiveBayes,x_test_1 ,y_test_1.values.ravel()) 

Leave One Out çapraz doğrulama skoru :  0.5804701627486437
5 katlı çapraz doğrulama skoru :  0.5810559458377316
10 katlı çapraz doğrulama skoru :  0.5810587805768529


In [ ]:
cv_skor_yaz(model_svm_rbf,x_test_1 ,y_test_1.values.ravel()) 

Leave One Out çapraz doğrulama skoru :  0.9144062688366486
5 katlı çapraz doğrulama skoru :  0.9132075128307793
10 katlı çapraz doğrulama skoru :  0.9138006571741512


In [ ]:
cv_skor_yaz(model_svm_linear,x_test_1 ,y_test_1.values.ravel()) 

Leave One Out çapraz doğrulama skoru :  0.9083785412899337
5 katlı çapraz doğrulama skoru :  0.9065719069632002
10 katlı çapraz doğrulama skoru :  0.9059620299379335
